apiVersion: v1
kind: Pod
metadata:
  name: aluna-ui
  labels:
    app: aluna-ui
spec:
  containers:
  - name: aluna-ui
    image: localhost/aluna-ui:latest
    ports:
    - containerPort: 8080
      hostPort: 4176
    env:
    - name: VITE_API_BASE_URL
      value: "https://aluna-api.deployhero.dev"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 3
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
  restartPolicy: Always
